version: '3.1'

services:

  jupyter:
    image: jupyter-gpu
    #command: pip install --no-input mysql-connector-python
    restart: always    
    volumes:
      - ./conf:/root/.jupyter
      - ./notebook:/notebook
      - ./logs:/usr/local/log
    ports:
      - "8080:8080"
    #environment:
    #  - JUPYTER_TOKEN=easy

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    container_name: jupyter



networks:
  default:
    external:
      name: dev_network
